branches:
  only: src
language: python
python: '3.6'
sudo: false
env:
  global:
    secure: Mnv+u4TqzcXYWGDVzUdsDkARbW1lG4avLFnmnIFdnvBP8GnwfXMPm8DZM6wUnnomIRk35CyZ0DanKbuWSBEhKp1XYuXyLEgSUWowJHzyZoyKoFZkrcOlBnY59dWqyHkvnHQChJpJ5n5oWOdrXFZNFw/sz/AsgWYV5ycMKPTk0O2MZw/wqKMXCxiB+z7OtTNLS2yp9QDu0CKMRrvE9ycM1gqs5egpmMQuIHp97BfMe6epw1xX/BkaL6SmjFPKpQQSsqiDj64yV56eGmAY7r+kjOmoSz+ctYBigLOEaCWhbSxbOxC7ORA5Hz1dtfhyrVUqXOe4KmXH/c7fvSJadXjmZQqmk87czVSPZox5XpTU72OhWdjcbBVSzB1uRJaVORHuKEwK5Z6DGwsC6XH9z7HjyG/2WHavNxR7jADcsht4/FvIpa0p5DIcLd3VpOXyMQiZ7vl4vBNVW84XStYu8ThF422F64qNrdzQ2TaHnoroEW30qqa/mX4oDGmiCVcW7qq/0a9yhUR5TldAhSCArYun7epkysAMFpEXz7JLek81L6uY1KRMjRWZaAfYZjoFn+4XAwTVcNMuw4Qc/UJDY7O8Mm0RjD4CUk/XynJtAvM7o+VMfdPvtu+qCyMr7ro6M4Si8/vKpt+pYi+UP+EsbVtZMEbxjIIdH6XFAWGrSzIeOX8=
cache: pip
install: make install
script: make build
after_success: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make diff; else make deploy; fi
