branches:
  only: src
language: python
python: '3.6'
sudo: false
env:
  global:
    secure: U+XvQb4XPtvSYumkf9Homd1RFc2Uc6TkLmTBtHoF+o4i322kNkxmqD32WsLgBsVAbmbrq8sBDR19YlrnGiaDQ+U1CBiBXLcU1x4dtFXmcseCPuPTV2bSz5SBv77A+B92gXLZIomEPkt60fsHAUAub9bi2awhUDEOUrpf5RDc2VauGpZTXm/MHsh75D0JJQe6+wztQaMphAWJKPnVvr+O8TkNK/XSxXt4tE9g/dpx+O2xpw4oTOkujfFiGFqBdVgq/fXQxwncHysMRKA1v+Rqujo3c3KNA68IxR+ELxnALAz+pzdoPIdj66p/iOcoRAihQuDSJJ6OLyJjpTxGSARqzg8X9HDyqIVXSFnpZLoWSvQ5fXzKuBl0C9q6hMsj6zjjbmCeHbNeOUpgJ06IrRPrOdQlVTFBq6dR5QDYpMX+76yqOfpL4s5Z+joVDZmb0iuc3jONM4XtHyXtIfnOzEJSDKSJBS7qfJBzjRH8717tc9N3a6Y8fdcvJB8kkjDGLuNLCu7McKzC66skGro8W2GS8CFiZplmu2Bz2CJfRjjTyEr1pWRw00fvhEVUCAEQECFbO6tgcswDshSTkrLohYrQsJWNff9KtKuEtForO1emSsskDwe1QnyMu1cqTanv5Op3WcNBGXRXqYP0yu6lbXXal8TgsAj58fPpcjUg6Jjm6tI=
cache: pip
install: make install
script: make build
after_success: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make diff; else make deploy; fi
