branches:
  only: src
language: python
python: '3.6'
sudo: false
cache: pip
install: make install
script: make build
after_success: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make diff; else make
  deploy; fi
env:
  global:
