title: jrf
baseurl: ""
url: ""
github_username: jrf

theme: jekyll-theme-chirpy

# Theme settings
avatar: ./assets/img/avatar.jpg
mode: dark

# Basic settings
timezone: America/New_York
lang: en

# Pagination
paginate: 10
paginate_path: /page:num/

# Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-spaceship

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      comments: false
      math: true

# Post settings
excerpt_separator: <!--more-->
show_excerpts: true

# Social links (adjust as needed)
social:
  name: jrf
  links:
    - https://github.com/jrf

# If you want to enable comments
comments:
  active: false

# If you want Google Analytics
google_analytics:
  id: # your id
  pv:
    enabled: false

# To avoid build warnings
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
